# Tools
brew 'bat'
brew 'coreutils' # Those that come with macOS are outdated
brew 'ffmpeg'
brew 'fastfetch'
brew 'gh'
brew 'git'
brew 'grep'
brew 'neovim'
brew 'zoxide'
brew 'zlib'

# Development
brew 'go'
brew 'rust'
brew 'awscli'
brew 'node'
brew 'redis'
brew 'pyenv'
brew 'lua'

# Applications
cask 'drawio'
cask 'jetbrains-toolbox'
cask 'appcleaner'
cask 'cloudflare-warp'
cask 'dbngin'
cask 'discord'
cask 'docker'
cask 'evkey'
cask 'kitty'
cask 'postman'
cask 'arc'
cask 'obsidian'
cask 'rar'
cask 'transmission'
cask 'telegram'
cask 'vlc'
cask 'visual-studio-code'
cask 'zalo'

# Fonts
cask 'font-mononoki-nerd-font'
